### PR TITLE
Feature/Deploy MongoDB

### LINKED ISSUE #11: Deploy MongoDB on Dev using an operator
Deploy MongoDB using a kubernetes operator. 

- MongoDB has an officially maintained [kubernetes operator for MongoDB community](https://github.com/mongodb/mongodb-kubernetes-operator). This operator can be used to install and deploy MongoDB in our cluster.

### PR DESCRIPTION
**Pull request by akkbng**
Hopefully fixes #11  :)
Still pretty much Work-in-Progress

### CODE REVIEW

**Comment by akkbng** [comment]
Do you have any pointers for me to see if I'm on the right direction for deploying this properly or not? @ldb @jgraeger 

I saw there's also MongoDB bundled in Bitnami Helm Chart, but I don't know if that's a better way of doing this.
- https://bitnami.com/stack/mongodb/helm
- https://github.com/bitnami/charts/tree/master/bitnami/mongodb/

**Comment by akkbng** [comment]
Do you have any pointers for me to see if I'm on the right direction for deploying this properly or not? @ldb @jgraeger 

I saw there's also MongoDB bundled in Bitnami Helm Chart, but I don't know if that's a better way of doing this.
- https://bitnami.com/stack/mongodb/helm
- https://github.com/bitnami/charts/tree/master/bitnami/mongodb/

**Comment by akkbng** [comment]
FYI: I'll switch to Bitnami Helm Chart for MongoDB @ldb @jgraeger

**Review by isaschm — APPROVED** [review]
Am I allowed to approve this? Either way ✅

**Review by ldb — COMMENTED** [review]
Before approving this, let's try actually deploying a database with this :)

**Review by ldb — APPROVED** [review]
:shipit:

**Pull request merged**
